name: linux tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HUSKY: 0

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Lint the Commit Messages
      uses: wagoid/commitlint-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Lint Files
      run: npm run lint

    - name: Run Tests
      env:
        CI: true
      run: npm test
